version: '3.7'
services:
  mysql:
    #   Opinionated image choice
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agreeable_chef
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306'

  rabbitmq:
    # Additional configuration may require a Dockerfile.
    image: 'rabbitmq:latest'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    volumes: # Plugin support will either need to use volumes and/or dockerfile

    ports:
      - '5672'
      - '15672'

  redis:
    image: 'redis:latest'
    ports:
      - '6379'
